name: deploy

on:
  push:
    branches: [prod]

concurrency:
  group: deploy#${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build CLI
        run: |
          npm ci
          npm run build:prod
      - name: Publish NPM package
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
