name: verify

on:
  push:
    branches-ignore: []
  pull_request:
    branches-ignore: []

concurrency:
  group: verify#${{ github.ref }}
  cancel-in-progress: true

jobs:
  samples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd cli
      - run: npm ci
      - run: npm run build:prod
      - run: cd samples
      - run: npm ci
      - run: npm run test:headless
