name: verify

on:
  push:
    # branches-ignore: [master]
  pull_request:
    # branches-ignore: [master]

concurrency:
  group: verify#${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cli
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:prod
  test-samples:
    build-cli:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: samples
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:headless
