name: verify

on:
  push:
    branches-ignore: [prod]
  pull_request:
    branches-ignore: [prod]

concurrency:
  group: verify#${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build CLI
        working-directory: cli
        run: |
          npm ci
          npm run build:prod
      - name: Test Samples
        working-directory: samples
        run: |
          npm ci
          npm run tests:headless
